[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm install && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://sasi-ece-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
